### PR TITLE
feat(kv): add missing methods for workers kv namespace

### PR DESCRIPTION
**Pull request by thebergamo**
Thank you for the project.

I have added the missing methods for the Workers KV to work, please let me know if my implementation makes sense with the guidelines of the project or if any changes are needed.

### CODE REVIEW

**Comment by johnspurlock-skymethod** [comment]
thanks! Can you limit your changes to functionality only instead of reformatting?  The cloudflare_api diff looks too big, appears to be mostly reformatting

**Comment by thebergamo** [comment]
Oh, that's prettier, let me check if I can disable it.

**Comment by thebergamo** [comment]
@johnspurlock-skymethod can you check now? Tried to keep it as close as possible to the original coding style.

**Comment by johnspurlock-skymethod** [comment]
Appreciate it - this is a good start so I'm happy to commit it.  I'll follow with a quick formatting commit to make it match the style.

- Typically I avoid `pipeThrough` since there are limitations when running on Workers (it didn't used to be supported at all), but this class is intended to run on the CLI side so I guess it's ok.
- This is will make KV available in `serve`, but only without hot reloading.  In order to support hot reload, we'll need to plumb this through in `rpc_kv_namespace.ts`.  This can be a followup, do you feel like tackling that as well?

**Comment by thebergamo** [comment]
Need to analyze it and check it, in my current development I'm not using the hot reload that much, but will take a look later today

**Pull request merged**
